apiVersion: v1
kind: Secret
metadata:
  name: zipbob-llm-secret
type: Opaque
data:
  PINECONE_API_KEY: "MmQzNzkwNzYtYjA3Yy00MDA2LThkNDEtMzMwNGRiYmFmNmY4"
  RECIPE_DB_API_KEY: "MWQxM2JiZDdjODFkNDc2OGJhZGI="
  OPENAI_API_KEY: "c2stcHJvai1YZUV6YnVLMnQ5TFR5V0czUHVIVmJFM0JIMGZxZHBjTWV6Y0IybGc1b0VVSzJjMzFoUUNubk1sdUNETUpxdVhzYjc1dVJGbVVUSFQzQmxia0ZKcXllVHkwLUR6MzFHQjZ0akFLbndjWkRadXRkaGFBNklETzZ0Z0dhTElvRnRud1l6N2Y0bDZCakM2dmdEYXl2dnJCcEdSYmxRTUE="

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zipbob-llm-config
data:
  RABBITMQ_HOST: "user:Gi2BvQXNWLOpwsXt@rabbitmq.rabbitmq.svc.cluster.local:5672"
  PINECONE_HOST_URL: "https://recipes-q2ewlsu.svc.aped-4627-b74a.pinecone.io"



