apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp2
  awsElasticBlockStore:
    volumeID: "vol-0019c499ed4d2c015"
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: vault-pv
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-gp2
