apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipbob-rabbitmq
  labels:
    db: zipbob-rabbitmq
spec:
  selector:
    matchLabels:
      db: zipbob-rabbitmq
  template:
    metadata:
      labels:
        db: zipbob-rabbitmq
    spec:
      containers:
        - name: zipbob-rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /etc/rabbitmq
              name: rabbitmq-config-volume
      volumes:
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-config

---

apiVersion: v1
kind: Service
metadata:
  name: zipbob-rabbitmq
  labels:
    db: zipbob-rabbitmq
spec:
  type: ClusterIP
  selector:
    db: zipbob-rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672