apiVersion: v1
kind: Service
metadata:
  namespace: rabbitmq
  name: rabbitmq-management-service
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmq-0
