services:

  # Applications

  zipbob-config-service:
    platform: linux/amd64
    depends_on:
      zipbob-vault:
        condition: service_started
      zipbob-rabbitmq:
        condition: service_started
    image: "zipbob-config-service"
    container_name: "zipbob-config-service"
    ports:
      - 8888:8888
      - 9888:9888
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 3s
      retries: 10
      timeout: 5s
      start_period: 5s
    env_file:
      ./common-config.env
    environment:
      - BPL_DEBUG_PORT=9888
      - THC_PORT=8888
      - THC_PATH=/actuator/health
      - SPRING_RABBITMQ_HOST=zipbob-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST=zipbob-vault
      - SPRING_CLOUD_CONFIG_SERVER_VAULT_PORT=8200
      - SPRING_CLOUD_VAULT_HOST=zipbob-vault
      - SPRING_CLOUD_VAULT_PORT=8200
      - SPRING_CLOUD_VAULT_URI=http://zipbob-vault:8200

  zipbob-edge-service:
    platform: linux/amd64
    depends_on:
      zipbob-vault:
        condition: service_started
      zipbob-mariadb:
        condition: service_started
      zipbob-redis:
        condition: service_started
      zipbob-rabbitmq:
        condition: service_started
      zipbob-config-service:
        condition: service_healthy
    image: "zipbob-edge-service"
    container_name: "zipbob-edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_DEBUG_PORT=8000
      - SPRING_CLOUD_CONFIG_URI=http://zipbob-config-service:8888
      - SPRING_PROFILES_ACTIVE=prod

  ingredients-manage-service:
    platform: linux/amd64
    depends_on:
      zipbob-mariadb:
        condition: service_started
      zipbob-config-service:
        condition: service_healthy
      zipbob-rabbitmq:
        condition: service_started
    image: "ingredients-manage-service"
    container_name: "ingredients-manage-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://zipbob-config-service:8888
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  recipe-review-service:
    platform: linux/amd64
    depends_on:
      zipbob-vault:
        condition: service_started
      zipbob-mongodb:
        condition: service_started
#      zipbob-rabbitmq:
#        condition: service_started
#      zipbob-config-service:
#        condition: service_healthy
    image: "recipe-review-service"
    container_name: "recipe-review-service"
    ports:
      - 9002:9002
      - 8002:8002
    env_file:
      ./common-config.env
    environment:
      - BPL_DEBUG_PORT=8002
      - vault_host=zipbob-vault
      - vault_port=8200
      - SPRING_CLOUD_VAULT_KV_PROFILES=docker

  # Backing Services

  zipbob-mariadb:
    image: "mariadb:latest"
    container_name: "zipbob-mariadb"
    ports:
      - 3306:3306
    env_file:
      - ./mariadb/mariadb.env
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  zipbob-redis:
    image: "redis:latest"
    container_name: "zipbob-redis"
    ports:
      - 6379:6379

  zipbob-rabbitmq:
    image: rabbitmq:latest
    container_name: zipbob-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  zipbob-mongodb:
    image: mongo:latest
    container_name: zipbob-mongodb
    ports:
      - 27017:27017
    env_file:
      - ./mongodb/mongodb.env

  zipbob-vault:
    image: hashicorp/vault:latest
    container_name: zipbob-vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
      - ./logs/config:/vault/logs
    environment:
      - SKIP_CHOWN=true
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/local.json