apiVersion: v1
kind: ConfigMap
metadata:
  name: recipe-review-service-configmap
data:
  BPL_DEBUG_PORT: "8002"
  vault_host: "zipbob-vault"
  vault_port: "8200"
  SPRING_CLOUD_VAULT_KV_PROFILES: "k8s"
#  SPRING_CLOUD_CONFIG_URI: "http://zipbob-config-service"
#  SPRING_CLOUD_CONFIG_FAIL_FAST: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-review-service
  labels:
    app: recipe-review-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: recipe-review-service
  template:
    metadata:
      labels:
        app: recipe-review-service
    spec:
      initContainers:
#      - name: init-zipbob-config-service
#        image: curlimages/curl
#        command: ['sh', '-c', 'until curl --fail http://zipbob-config-service/actuator/health; do echo waiting for zipbob-config-service; sleep 2; done']
      - name: init-zipbob-vault
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z zipbob-vault 8200; do echo waiting for zipbob-vault; sleep 2; done']
      - name: init-zipbob-mongodb
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z mongodb-0.mongodb-service.mongodb.svc.cluster.local 27017; do echo waiting for mongodb-0; sleep 2; done']
      containers:
        - name: recipe-review-service
          image: ghcr.io/kakao-tech-bootcamp-team2/recipe-review-service
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
            - containerPort: 8002
          envFrom:
          - configMapRef:
              name: recipe-review-service-configmap
          - configMapRef:
              name: common-configmap
          env:
            - name: vault_token
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: vault_token
          resources:
            requests:
              memory: "100Mi"    
              cpu: "100m"     
              ephemeral-storage: "2Gi"


---

apiVersion: v1
kind: Service
metadata:
  name: recipe-review-service
  labels:
    app: recipe-review-service
spec:
  type: LoadBalancer
  selector:
    app: recipe-review-service
  ports:
    - name: http
      protocol: TCP
      port: 9002
      targetPort: 9002
    - name: debug
      protocol: TCP
      port: 8001
      targetPort: 8002

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: recipe-review-service-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recipe-review-service
  updatePolicy:
    updateMode: "Off"