apiVersion: v1
kind: ConfigMap
metadata:
  name: zipbob-config-server-configmap
data:
  BPL_DEBUG_PORT: "9888"
  THC_PORT: "8888"
  THC_PATH: "/actuator/health"
  SPRING_RABBITMQ_HOST: "zipbob-rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST: "zipbob-vault"
  SPRING_CLOUD_CONFIG_SERVER_VAULT_PORT: "8200"
  SPRING_CLOUD_VAULT_HOST: "zipbob-vault"
  SPRING_CLOUD_VAULT_PORT: "8200"
  SPRING_CLOUD_VAULT_URI: "http://zipbob-vault:8200"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipbob-config-service
  labels:
    app: zipbob-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipbob-config-service
  template:
    metadata:
      labels:
        app: zipbob-config-service
    spec:
      initContainers:
        - name: init-zipbob-vault
          image: busybox:1.31
          command: ['sh', '-c', 'until nc -z zipbob-vault 8200; do echo waiting for zipbob-vault; sleep 2; done']
        - name: init-zipbob-rabbitmq
          image: busybox:1.31
          command: ['sh', '-c', 'until nc -z zipbob-rabbitmq 5672; do echo waiting for zipbob-rabbitmq; sleep 2; done']
      containers:
        - name: zipbob-config-service
          image: zipbob-config-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
            - containerPort: 9888
          envFrom:
            - configMapRef:
                name: zipbob-config-server-configmap
            - configMapRef:
                name: common-configmap
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: vault_token
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

---

apiVersion: v1
kind: Service
metadata:
  name: zipbob-config-service
  labels:
    app: zipbob-config-service
spec:
  type: ClusterIP
  selector:
    app: zipbob-config-service
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: debug
      protocol: TCP
      port: 9888
      targetPort: 9888
