apiVersion: v1
kind: ConfigMap
metadata:
  name: zipbob-config-server-configmap
data:
  BPL_JVM_THREAD_COUNT: "50"
  SPRING_PROFILES_ACTIVE: "native"
  BPL_DEBUG_ENABLED: "true"
  BPL_DEBUG_PORT: "9888"
  NATIVE_LOCATION: "/config"
  THC_PORT: "8888"
  THC_PATH: "/actuator/health"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipbob-config-service
  labels:
    app: zipbob-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipbob-config-service
  template:
    metadata:
      labels:
        app: zipbob-config-service
    spec:
      containers:
      - name: zipbob-config-service
        image: zipbob-config-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        - containerPort: 9888
        envFrom:
        - configMapRef:
            name: zipbob-config-server-configmap
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        volumeMounts:
        - name: config-volume
          mountPath: /config
        readinessProbe:
          exec:
            command:
              - /workspace/health-check
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 20
      volumes:
      - name: config-volume
        hostPath:
          # 개발환경의 Local native 저장소의 절대 경로 위치로 수정해야 합니다.
          path: /Users/sindongseong/DsStudy/zipbob/native-config-repo
          type: Directory


---

apiVersion: v1
kind: Service
metadata:
  name: zipbob-config-service
  labels:
    app: zipbob-config-service
spec:
  type: ClusterIP
  selector:
    app: zipbob-config-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
    - name: debug
      protocol: TCP
      port: 9888
      targetPort: 9888


