apiVersion: v1
kind: ConfigMap
metadata:
  name: ingredients-manage-service-configmap
data:
  BPL_JVM_THREAD_COUNT: "50"
  BPL_DEBUG_ENABLED: "true"
  BPL_DEBUG_PORT: "8001"
  SPRING_CLOUD_CONFIG_URI: "http://zipbob-config-service"
  SPRING_DATASOURCE_URL: "jdbc:mariadb://zipbob-mariadb:80/members"
  SPRING_RABBITMQ_HOST: "zipbob-rabbitmq"
  SPRING_RABBITMQ_PORT: "80"
  SPRING_CLOUD_CONFIG_FAIL_FAST: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients-manage-service
  labels:
    app: ingredients-manage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredients-manage-service
  template:
    metadata:
      labels:
        app: ingredients-manage-service
    spec:
      initContainers:
      - name: init-zipbob-config-service
        image: curlimages/curl
        command: ['sh', '-c', 'until curl --fail http://zipbob-config-service/actuator/health; do echo waiting for zipbob-config-service; sleep 2; done']
      - name: init-zipbob-mariadb
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z zipbob-mariadb 80; do echo waiting for zipbob-mariadb; sleep 2; done']
      - name: init-zipbob-rabbitmq
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z zipbob-rabbitmq 80; do echo waiting for zipbob-rabbitmq; sleep 2; done']
      containers:
        - name: ingredients-manage-service
          image: ingredients-manage-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
            - containerPort: 8001
          envFrom:
          - configMapRef:
              name: ingredients-manage-service-configmap
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]

---

apiVersion: v1
kind: Service
metadata:
  name: ingredients-manage-service
  labels:
    app: ingredients-manage-service
spec:
  type: ClusterIP
  selector:
    app: ingredients-manage-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9001
    - name: debug
      protocol: TCP
      port: 8001
      targetPort: 8001
