apiVersion: v1
kind: ConfigMap
metadata:
  name: ingredients-manage-service-configmap
data:
  BPL_DEBUG_PORT: "8001"
  SPRING_CLOUD_CONFIG_URI: "http://zipbob-config-service:8888"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update" #DB와 Storage 분리할 때까지

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients-manage-service
  labels:
    app: ingredients-manage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredients-manage-service
  template:
    metadata:
      labels:
        app: ingredients-manage-service
    spec:
      initContainers:
      - name: init-zipbob-config-service
        image: curlimages/curl
        command: ['sh', '-c', 'until curl --fail http://zipbob-config-service:8888/actuator/health; do echo waiting for zipbob-config-service; sleep 2; done']
      - name: init-zipbob-mariadb
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z zipbob-mariadb 3306; do echo waiting for zipbob-mariadb; sleep 2; done']
      - name: init-zipbob-rabbitmq
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -z zipbob-rabbitmq 5672; do echo waiting for zipbob-rabbitmq; sleep 2; done']
      containers:
        - name: ingredients-manage-service
          image: ingredients-manage-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
            - containerPort: 8001
          envFrom:
          - configMapRef:
              name: ingredients-manage-service-configmap
          - configMapRef:
              name: common-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: ingredients-manage-service
  labels:
    app: ingredients-manage-service
spec:
  type: ClusterIP
  selector:
    app: ingredients-manage-service
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: debug
      protocol: TCP
      port: 8001
      targetPort: 8001
