apiVersion: v1
kind: Service
metadata:
  namespace: mariadb
  name: mariadb-loadbalancer-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: mariadb-0
